 08/20/21 19:41:43 Database gtSI_4cyl_Ba_10515efo created
 ==============================================================================
 GT-SUITE - GAMMA TECHNOLOGIES
 ------------------------------------------------------------------------------
 License  :  GT-POWER
 Version  :  2016
 Build #  :  3.0000
 Platform :  Windows 64 bit
 Parallel :  2 MAX OpenMP Threads
 Date     :  20-AUG-21  Time: 19:41:43
 File     :  C:\Users\ASUS\Desktop\SI_4cyl_Basic.dat
 ==============================================================================
 INFO  Shared object versions used:
   C:\PROGRA~2\GTI\bin\win64\GTIusr2016_64_mp.dll            3.0000
   C:\PROGRA~2\GTI\v2016\GTsuite\bin\win64\gtstoredp.dll     3.0000
   C:\PROGRA~2\GTI\v2016\GTsuite\bin\win64\gtmt.dll          3.0000
   (Note the user dll/so build number need not match the solver)
 INFO Allocating Object/Part memory...
 INFO Allocating special part array memory...
  LEGEND: Four-Cylinder SI Engine Example                                                                                           
 INFO Part defining periodic process: Engine
 INFO Total number of pipe sub-volumes =  154
 INFO Total number of flow volumes     =  232
*INFO: Estimated animation file size is  5 MB.
 INFO Total Number of Parts =  346
  Case Number:        1 of  2
  Case Setup Number:  1
 MAIN DRIVER: Case# 1  Period# 1  Freq/RPM=100. 6000.  Time=0.0
   Cylinder  1 starting cycle 1
 Flow Step       20, dt =   2.343E-05, t =  4.76661E-04
 Flow Step       40, dt =   2.301E-05, t =  9.37757E-04
 Flow Step       60, dt =   2.296E-05, t =  1.39856E-03
 Flow Step       80, dt =   2.231E-05, t =  1.85131E-03
   Cylinder  3 starting cycle 1
   Cylinder  4 starting cycle 1
   Cylinder  2 starting cycle 1
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.095    8.97   42.63    17.1   0.0   0.0909
     Cylinder-02:    1.106   12.24   75.43    23.5   2.8   0.0000
     Cylinder-03:    0.636   15.13   70.02    57.9   0.0   0.0822
     Cylinder-04:    1.018   13.62   68.45    26.3   3.1   0.1122
     ENGINE: IMEP =     12.49 bar, VOLEF = 0.964 VOLEFm = 0.964
    Flow timesteps/cycle=966, average time step =    0.745 deg
    Time step restricted by the following flow components 
      mufHS0213:  57.5%
      mufHS0109:  40.8%
 MAIN DRIVER: Case# 1  Period# 2  Freq/RPM=100. 6000.  Time=2.E-02
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.071   14.81   74.54    33.6   2.6   0.1018
     Cylinder-02:    1.049   14.46   72.94    32.5   3.3   0.0992
     Cylinder-03:    1.048   14.67   71.57    39.3   2.9   0.0706
     Cylinder-04:    1.036   14.10   71.16    28.8   3.2   0.1003
     ENGINE: IMEP =     14.51 bar, VOLEF = 1.051 VOLEFm = 1.051
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1067, average time step =    0.675 deg
    Time step restricted by the following flow components 
      mufHS0213:  53.1%
      mufHS0109:  45.5%
 MAIN DRIVER: Case# 1  Period# 3  Freq/RPM=100. 6000.  Time=4.E-02
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.069   14.82   74.32    32.7   3.2   0.0830
     Cylinder-02:    1.043   14.28   72.48    31.2   3.2   0.0860
     Cylinder-03:    1.018   14.06   70.81    32.7   3.0   0.0842
     Cylinder-04:    1.043   14.30   72.24    31.2   3.2   0.0903
     ENGINE: IMEP =     14.36 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1092, average time step =    0.659 deg
    Time step restricted by the following flow components 
      mufHS0213:  57.1%
      mufHS0109:  41.6%
 MAIN DRIVER: Case# 1  Period# 4  Freq/RPM=100. 6000.  Time=6.E-02
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.071   14.73   74.12    32.2   3.1   0.0857
     Cylinder-02:    1.047   14.32   72.77    31.3   3.1   0.0896
     Cylinder-03:    1.021   13.97   70.77    31.0   3.2   0.0897
     Cylinder-04:    1.035   14.19   71.75    31.3   3.1   0.0895
     ENGINE: IMEP =     14.30 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1089, average time step =    0.661 deg
    Time step restricted by the following flow components 
      mufHS0213:  60.3%
      mufHS0109:  38.4%
 MAIN DRIVER: Case# 1  Period# 5  Freq/RPM=100. 6000.  Time=8.E-02
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.072   14.76   74.24    32.3   3.0   0.0863
     Cylinder-02:    1.047   14.35   72.80    31.4   3.1   0.0892
     Cylinder-03:    1.020   13.94   70.67    30.5   3.2   0.0918
     Cylinder-04:    1.034   14.18   71.65    31.1   3.1   0.0901
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.044 VOLEFm = 1.044
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1081, average time step =    0.666 deg
    Time step restricted by the following flow components 
      mufHS0213:  61.7%
      mufHS0109:  37.1%
 MAIN DRIVER: Case# 1  Period# 6  Freq/RPM=100. 6000.  Time=0.1
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.79   74.31    32.3   3.0   0.0863
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0890
     Cylinder-03:    1.020   13.93   70.63    30.5   3.2   0.0924
     Cylinder-04:    1.034   14.17   71.61    31.0   3.0   0.0905
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1080, average time step =    0.667 deg
 MAIN DRIVER: Case# 1  Period# 7  Freq/RPM=100. 6000.  Time=0.12
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.34    32.3   3.0   0.0862
     Cylinder-02:    1.048   14.36   72.80    31.4   3.1   0.0890
     Cylinder-03:    1.020   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.60    31.0   3.0   0.0906
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1076, average time step =    0.669 deg
 MAIN DRIVER: Case# 1  Period# 8  Freq/RPM=100. 6000.  Time=0.14
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.35    32.4   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0890
     Cylinder-03:    1.020   13.93   70.64    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.59    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1073, average time step =    0.671 deg
 MAIN DRIVER: Case# 1  Period# 9  Freq/RPM=100. 6000.  Time=0.16
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.4   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0890
     Cylinder-03:    1.020   13.93   70.64    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.59    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1073, average time step =    0.671 deg
 MAIN DRIVER: Case# 1  Period# 10  Freq/RPM=100. 6000.  Time=0.18
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.4   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.020   13.93   70.64    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.59    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1072, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 11  Freq/RPM=100. 6000.  Time=0.2
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.4   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.64    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.59    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1072, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 12  Freq/RPM=100. 6000.  Time=0.22
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.4   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.64    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.59    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 13  Freq/RPM=100. 6000.  Time=0.24
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.4   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 14  Freq/RPM=100. 6000.  Time=0.26
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.4   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 15  Freq/RPM=100. 6000.  Time=0.28
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 16  Freq/RPM=100. 6000.  Time=0.3
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 17  Freq/RPM=100. 6000.  Time=0.32
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 18  Freq/RPM=100. 6000.  Time=0.34
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 19  Freq/RPM=100. 6000.  Time=0.36
 Flow Step    20000, dt =   1.872E-05, t =  0.37424
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 20  Freq/RPM=100. 6000.  Time=0.38
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 21  Freq/RPM=100. 6000.  Time=0.4
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 22  Freq/RPM=100. 6000.  Time=0.42
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 23  Freq/RPM=100. 6000.  Time=0.44
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 24  Freq/RPM=100. 6000.  Time=0.46
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 25  Freq/RPM=100. 6000.  Time=0.48
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 26  Freq/RPM=100. 6000.  Time=0.5
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 27  Freq/RPM=100. 6000.  Time=0.52
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 28  Freq/RPM=100. 6000.  Time=0.54
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 29  Freq/RPM=100. 6000.  Time=0.56
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 30  Freq/RPM=100. 6000.  Time=0.58
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 MAIN DRIVER: Case# 1  Period# 31  Freq/RPM=100. 6000.  Time=0.6
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
 INFO Requested number of periods reset to =  32
 MAIN DRIVER: Case# 1  Period# 32  Freq/RPM=100. 6000.  Time=0.62
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    1.073   14.80   74.36    32.3   2.9   0.0862
     Cylinder-02:    1.047   14.36   72.80    31.4   3.1   0.0891
     Cylinder-03:    1.019   13.93   70.63    30.4   3.2   0.0925
     Cylinder-04:    1.034   14.17   71.58    31.0   3.0   0.0907
     ENGINE: IMEP =     14.31 bar, VOLEF = 1.043 VOLEFm = 1.043
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1071, average time step =    0.672 deg
    Time step restricted by the following flow components 
      mufHS0213:  66.3%
      mufHS0109:  32.6%
 INFO Number of flow time steps in this case = 34232
  ...STORING ANIMATION DATA
      20% Complete
      40% Complete
      60% Complete
      80% Complete
     100% Complete
  CASE    COMPUTATIONS:  Elapsed Time: 000:00:43.51
 INFO Allocating Object/Part memory...
 INFO Allocating special part array memory...
  LEGEND: Four-Cylinder SI Engine Example                                                                                           
 INFO Part defining periodic process: Engine
 INFO Total number of pipe sub-volumes =  154
 INFO Total number of flow volumes     =  232
*INFO: Estimated animation file size is  5 MB.
 INFO Total Number of Parts =  346
  Case Number:        2 of  2
  Case Setup Number:  5
 MAIN DRIVER: Case# 2  Period# 1  Freq/RPM=66.6667 4000.  Time=0.0
   Cylinder  1 starting cycle 1
 Flow Step       20, dt =   1.888E-05, t =  3.76949E-04
 Flow Step       40, dt =   1.894E-05, t =  7.55159E-04
 Flow Step       60, dt =   1.878E-05, t =  1.13278E-03
 Flow Step       80, dt =   1.860E-05, t =  1.50630E-03
   Cylinder  3 starting cycle 1
   Cylinder  4 starting cycle 1
   Cylinder  2 starting cycle 1
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.881   15.13   74.06    38.3   2.9   0.0862
     Cylinder-02:    0.860   12.49   57.94    30.9   3.1   0.0891
     Cylinder-03:    1.111   12.78   62.15    22.1   3.2   0.0777
     Cylinder-04:    0.808   10.98   53.99    26.7   3.6   0.1121
     ENGINE: IMEP =     12.84 bar, VOLEF = 0.915 VOLEFm = 0.915
   RLT STEADY STATE:
    Flow timesteps/cycle=1533, average time step =    0.470 deg
    Time step restricted by the following flow components 
      mufHS0213:  70.5%
      mufHS0109:  28.7%
 MAIN DRIVER: Case# 2  Period# 2  Freq/RPM=66.6667 4000.  Time=3.E-02
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.973   12.33   65.06    27.5   3.3   0.0921
     Cylinder-02:    0.898   12.55   66.45    31.7   3.1   0.0986
     Cylinder-03:    0.937   12.21   65.76    27.0   3.5   0.1203
     Cylinder-04:    0.948   13.61   70.67    37.0   3.7   0.0776
     ENGINE: IMEP =     12.68 bar, VOLEF = 0.939 VOLEFm = 0.939
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1443, average time step =    0.499 deg
    Time step restricted by the following flow components 
      mufHS0213:  62.7%
      mufHS0109:  36.5%
 MAIN DRIVER: Case# 2  Period# 3  Freq/RPM=66.6667 4000.  Time=6.E-02
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.983   13.65   72.54    34.0   3.5   0.0958
     Cylinder-02:    0.909   12.79   66.84    31.2   2.8   0.0907
     Cylinder-03:    0.919   12.88   67.41    32.1   3.1   0.0911
     Cylinder-04:    0.972   13.86   72.30    34.5   3.2   0.0825
     ENGINE: IMEP =     13.29 bar, VOLEF = 0.946 VOLEFm = 0.946
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1454, average time step =    0.495 deg
    Time step restricted by the following flow components 
      mufHS0213:  59.8%
      mufHS0109:  39.4%
 MAIN DRIVER: Case# 2  Period# 4  Freq/RPM=66.6667 4000.  Time=9.E-02
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.984   14.05   73.12    35.1   3.2   0.0821
     Cylinder-02:    0.910   12.85   66.97    32.0   2.8   0.0934
     Cylinder-03:    0.922   13.01   67.84    32.5   2.8   0.0889
     Cylinder-04:    0.979   13.98   72.78    34.6   3.2   0.0826
     ENGINE: IMEP =     13.47 bar, VOLEF = 0.949 VOLEFm = 0.949
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1447, average time step =    0.498 deg
    Time step restricted by the following flow components 
      mufHS0213:  58.9%
      mufHS0109:  40.2%
 MAIN DRIVER: Case# 2  Period# 5  Freq/RPM=66.6667 4000.  Time=0.12
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.08    35.1   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.11    32.2   2.8   0.0905
     Cylinder-03:    0.923   13.07   68.08    32.6   2.7   0.0886
     Cylinder-04:    0.980   14.00   72.79    34.9   3.2   0.0817
     ENGINE: IMEP =     13.51 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1439, average time step =    0.500 deg
    Time step restricted by the following flow components 
      mufHS0213:  58.7%
      mufHS0109:  40.4%
 MAIN DRIVER: Case# 2  Period# 6  Freq/RPM=66.6667 4000.  Time=0.15
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.11    35.2   3.0   0.0811
     Cylinder-02:    0.913   12.91   67.13    32.3   2.8   0.0897
     Cylinder-03:    0.924   13.09   68.14    32.7   2.7   0.0881
     Cylinder-04:    0.980   14.01   72.79    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1432, average time step =    0.503 deg
 MAIN DRIVER: Case# 2  Period# 7  Freq/RPM=66.6667 4000.  Time=0.18
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.91   67.13    32.3   2.8   0.0897
     Cylinder-03:    0.925   13.09   68.16    32.7   2.7   0.0880
     Cylinder-04:    0.980   14.01   72.81    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1431, average time step =    0.503 deg
 MAIN DRIVER: Case# 2  Period# 8  Freq/RPM=66.6667 4000.  Time=0.21
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.91   67.13    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.7   0.0880
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1428, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 9  Freq/RPM=66.6667 4000.  Time=0.24
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.7   0.0880
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1427, average time step =    0.505 deg
 MAIN DRIVER: Case# 2  Period# 10  Freq/RPM=66.6667 4000.  Time=0.27
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.7   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1428, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 11  Freq/RPM=66.6667 4000.  Time=0.3
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.7   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 12  Freq/RPM=66.6667 4000.  Time=0.33
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 13  Freq/RPM=66.6667 4000.  Time=0.36
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1430, average time step =    0.503 deg
 MAIN DRIVER: Case# 2  Period# 14  Freq/RPM=66.6667 4000.  Time=0.39
 Flow Step    20000, dt =   2.110E-05, t =  0.41619
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1430, average time step =    0.503 deg
 MAIN DRIVER: Case# 2  Period# 15  Freq/RPM=66.6667 4000.  Time=0.42
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 16  Freq/RPM=66.6667 4000.  Time=0.45
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 17  Freq/RPM=66.6667 4000.  Time=0.48
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.12    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 18  Freq/RPM=66.6667 4000.  Time=0.51
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.13    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
 MAIN DRIVER: Case# 2  Period# 19  Freq/RPM=66.6667 4000.  Time=0.54
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.13    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
 INFO Requested number of periods reset to =  20
 MAIN DRIVER: Case# 2  Period# 20  Freq/RPM=66.6667 4000.  Time=0.57
                     VOLEF   IMEP    Pmax     Ieff   REScs FAeff
     Cylinder-01:    0.985   14.07   73.10    35.2   3.1   0.0810
     Cylinder-02:    0.912   12.90   67.13    32.3   2.8   0.0896
     Cylinder-03:    0.925   13.09   68.16    32.7   2.8   0.0879
     Cylinder-04:    0.980   14.01   72.80    35.0   3.2   0.0815
     ENGINE: IMEP =     13.52 bar, VOLEF = 0.950 VOLEFm = 0.950
   FLOW STEADY STATE:
   RLT STEADY STATE:
    Flow timesteps/cycle=1429, average time step =    0.504 deg
    Time step restricted by the following flow components 
      mufHS0213:  55.7%
      mufHS0109:  43.3%
 INFO Number of flow time steps in this case = 28754
  ...STORING ANIMATION DATA
      20% Complete
      40% Complete
      60% Complete
      80% Complete
     100% Complete
  CASE    COMPUTATIONS:  Elapsed Time: 000:00:34.21
  FINAL   COMPUTATIONS:  Elapsed Time: 000:01:19.82
 END OF RUN
 08/20/21 19:43:08 Creating results (.gdx) file...
 08/20/21 19:43:12 SI_4cyl_Basic.gdx created.
